/**
 * LEV-183 unit tests — `.env.<service>` writer.
 *
 * Two layers covered:
 *
 *  1. {@link formatEnvFile} — pure formatter. Asserts the dotenv escape rules
 *     hold for every special character the spec calls out (whitespace,
 *     quotes, newlines, `=`, `#`, `\`). Pinned timestamp so the header is
 *     deterministic.
 *  2. {@link writeEnvFile} — disk-touching wrapper. Asserts parent-dir
 *     creation, UTF-8 round-trip, and overwrite semantics (re-running `dev`
 *     replaces the file, never appends — the post-LEV-182 generator MUST be
 *     idempotent).
 */
import { describe, it, expect, beforeEach } from 'vitest';
import { mkdtempSync, readFileSync, statSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { formatEnvFile, writeEnvFile } from '../../src/env/writer';

const FIXED_NOW = new Date('2026-05-17T12:34:56.000Z');

let tmpDir: string;

beforeEach(() => {
  tmpDir = realpathSync(mkdtempSync(join(tmpdir(), 'lz-envwriter-')));
});

describe('formatEnvFile', () => {
  it('emits the header with the ISO timestamp and the regenerate hint', () => {
    const out = formatEnvFile({}, FIXED_NOW);
    expect(out).toContain(
      '# generated by lich dev on 2026-05-17T12:34:56.000Z — DO NOT EDIT',
    );
    expect(out).toContain('# regenerate via: lich env resolve <service>');
    // Header only when env is empty + trailing newline.
    expect(out.endsWith('\n')).toBe(true);
  });

  it('emits bare KEY=value for safe values', () => {
    const out = formatEnvFile(
      {
        SIMPLE: 'value',
        URL: 'http://localhost:3000',
        NUMERIC: '42',
      },
      FIXED_NOW,
    );
    expect(out).toContain('SIMPLE=value');
    expect(out).toContain('URL=http://localhost:3000');
    expect(out).toContain('NUMERIC=42');
  });

  it('quotes values containing whitespace', () => {
    const out = formatEnvFile({ KEY: 'value with spaces' }, FIXED_NOW);
    expect(out).toContain('KEY="value with spaces"');
  });

  it('quotes values containing `=`', () => {
    // Without quoting, a downstream dotenv parser would split on the first
    // `=` only, but emitting `KEY=a=b` bare is brittle — quote to be safe.
    const out = formatEnvFile({ KEY: 'a=b=c' }, FIXED_NOW);
    expect(out).toContain('KEY="a=b=c"');
  });

  it('quotes values containing `#` so they aren\'t treated as comments', () => {
    const out = formatEnvFile({ COLOR: '#ff00ff' }, FIXED_NOW);
    expect(out).toContain('COLOR="#ff00ff"');
  });

  it('escapes embedded double quotes as \\"', () => {
    const out = formatEnvFile({ KEY: 'say "hi"' }, FIXED_NOW);
    expect(out).toContain('KEY="say \\"hi\\""');
  });

  it('escapes newlines as literal \\n inside quotes (single-line per entry)', () => {
    // Real \n must NOT survive into the file — downstream `source` / dotenv
    // parsers would break on it. Use literal backslash-n.
    const out = formatEnvFile({ MSG: 'line1\nline2' }, FIXED_NOW);
    expect(out).toContain('MSG="line1\\nline2"');
    // Critically: the file must not contain a real newline inside the value.
    const valueLines = out
      .split('\n')
      .filter((l) => l.startsWith('MSG='));
    expect(valueLines).toHaveLength(1);
  });

  it('escapes carriage returns as \\r', () => {
    const out = formatEnvFile({ MSG: 'line1\rline2' }, FIXED_NOW);
    expect(out).toContain('MSG="line1\\rline2"');
  });

  it('escapes backslashes (before other escapes so they don\'t double)', () => {
    // The implementation runs the `\` → `\\` substitution first so we don't
    // turn an authored `\n` (two chars) into `\\\n` (four chars + real
    // newline). Verify the round-trip is faithful: one authored backslash →
    // two file backslashes.
    const out = formatEnvFile({ KEY: 'a\\b' }, FIXED_NOW);
    expect(out).toContain('KEY="a\\\\b"');
  });

  it('emits one line per entry in insertion order with trailing newline', () => {
    const out = formatEnvFile(
      { FIRST: 'a', SECOND: 'b', THIRD: 'c' },
      FIXED_NOW,
    );
    const lines = out.split('\n');
    // Two header lines, three entries, trailing newline → 6 elements when
    // split (last one empty after the trailing \n).
    expect(lines[0]).toMatch(/^# generated by lich/);
    expect(lines[1]).toMatch(/^# regenerate via:/);
    expect(lines[2]).toBe('FIRST=a');
    expect(lines[3]).toBe('SECOND=b');
    expect(lines[4]).toBe('THIRD=c');
    expect(lines[5]).toBe('');
  });
});

describe('writeEnvFile', () => {
  it('writes the file at the given absolute path with UTF-8 contents', async () => {
    const path = join(tmpDir, 'api.env');
    await writeEnvFile(path, { DATABASE_URL: 'postgres://u:p@db:5432/x' });
    const content = readFileSync(path, 'utf8');
    expect(content).toContain('DATABASE_URL=postgres://u:p@db:5432/x');
  });

  it('creates any missing parent directories', async () => {
    // Mirrors the production layout: `.lich/state/<wt>/env/<svc>.env`
    // where neither `state/`, `<wt>/`, nor `env/` exist on first dev run.
    const path = join(tmpDir, '.lich', 'state', 'wt-abc123', 'env', 'api.env');
    await writeEnvFile(path, { KEY: 'value' });
    expect(statSync(path).isFile()).toBe(true);
  });

  it('overwrites on re-write (no append)', async () => {
    // The acceptance for LEV-183: re-running `dev` produces a clean snapshot,
    // never a growing log of past runs.
    const path = join(tmpDir, 'svc.env');
    await writeEnvFile(path, { OLD: 'gone', SHARED: 'first' });
    await writeEnvFile(path, { SHARED: 'second', NEW: 'here' });
    const content = readFileSync(path, 'utf8');
    expect(content).not.toContain('OLD=');
    expect(content).toContain('SHARED=second');
    expect(content).toContain('NEW=here');
    // Exactly one body block (two header lines plus the two values + trailing
    // newline = 5 lines on split).
    expect(content.split('\n').filter((l) => l.startsWith('# generated'))).toHaveLength(1);
  });

  it('handles the full special-char zoo end-to-end through disk', async () => {
    const path = join(tmpDir, 'zoo.env');
    await writeEnvFile(path, {
      SPACES: 'has spaces',
      QUOTED: 'has "quotes"',
      NEWLINE: 'line1\nline2',
      HASH: '#hex',
      EQUALS: 'a=b',
      BACKSLASH: 'a\\b',
    });
    const content = readFileSync(path, 'utf8');
    expect(content).toContain('SPACES="has spaces"');
    expect(content).toContain('QUOTED="has \\"quotes\\""');
    expect(content).toContain('NEWLINE="line1\\nline2"');
    expect(content).toContain('HASH="#hex"');
    expect(content).toContain('EQUALS="a=b"');
    expect(content).toContain('BACKSLASH="a\\\\b"');
  });
});
