import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { RouteEntry } from '../backend/types';
import type {
  FrontendAdapter,
  GenerateClientInput,
} from './types';

/**
 * Convert a route path into a CamelCase token for a function-name suffix.
 *
 * Examples:
 *   '/api/health'      -> 'ApiHealth'
 *   '/api/users/:id'   -> 'ApiUsersById'
 *   '/'                -> 'Root'
 */
function pathToCamelCase(path: string): string {
  const segments = path
    .split('/')
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((seg) => {
      // Strip param prefix ':' and prepend 'By' so `:id` -> `ById`.
      if (seg.startsWith(':')) {
        const name = seg.slice(1);
        if (name.length === 0) return '';
        return 'By' + name.charAt(0).toUpperCase() + name.slice(1);
      }
      // Sanitize any other non-identifier chars.
      const cleaned = seg.replace(/[^A-Za-z0-9]/g, '');
      if (cleaned.length === 0) return '';
      return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
    })
    .filter((s) => s.length > 0);

  if (segments.length === 0) return 'Root';
  return segments.join('');
}

function fnNameFor(route: RouteEntry): string {
  return route.method.toLowerCase() + pathToCamelCase(route.path);
}

function renderFunction(route: RouteEntry): string {
  const name = fnNameFor(route);
  const method = route.method;
  const isGet = method === 'GET' || method === 'HEAD';
  const initLine = isGet
    ? `  const r = await fetch(\`\${client.baseUrl}${route.path}\`);`
    : `  const r = await fetch(\`\${client.baseUrl}${route.path}\`, { method: '${method}' });`;
  return [
    `export async function ${name}(client: ApiClient): Promise<unknown> {`,
    initLine,
    '  if (!r.ok) throw new Error(`request failed: ${r.status}`);',
    '  return r.json();',
    '}',
  ].join('\n');
}

function renderFile(routes: RouteEntry[]): string {
  const header = [
    '// auto-generated by levelzero gen client',
    '// DO NOT EDIT BY HAND.',
    '',
    'export interface ApiClient {',
    '  baseUrl: string;',
    '}',
    '',
  ].join('\n');

  if (routes.length === 0) return header;

  const body = routes.map(renderFunction).join('\n\n');
  return header + body + '\n';
}

export const typedClientFrontendAdapter: FrontendAdapter = {
  name: 'typed-client',

  async generateClient(input: GenerateClientInput): Promise<{ files: string[] }> {
    const { routes, outDir } = input;
    await mkdir(outDir, { recursive: true });
    const filePath = join(outDir, 'index.ts');
    const contents = renderFile(routes.routes);
    await writeFile(filePath, contents, 'utf8');
    return { files: [filePath] };
  },
};
