import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parse as yamlParse } from "yaml";
import type { LichConfig, PortDescriptor } from "../../../src/config/types.js";
import {
  generateComposeOverride,
  writeComposeOverride,
  type OverrideInput,
} from "../../../src/compose/override.js";
import { stackDir } from "../../../src/state/directory.js";

function makeConfig(
  services: Record<string, unknown>,
): LichConfig {
  return {
    version: "1",
    services: services as NonNullable<LichConfig["services"]>,
  };
}

const SINGLE_SERVICE_CONFIG = makeConfig({
  api: {
    image: "node:20",
    ports: {
      http: { container: 3000, env: "PORT" },
    },
  },
});

const SINGLE_SERVICE_INPUT: OverrideInput = {
  config: SINGLE_SERVICE_CONFIG,
  allocatedPorts: {
    compose: {
      api: { http: 5847 },
    },
  },
  resolvedEnv: {
    api: {
      DATABASE_URL: "postgresql://user:pass@localhost:5432/db",
      LICH_STACK_ID: "dogfood-stack-a1b2c3d4",
    },
  },
  stackId: "dogfood-stack-a1b2c3d4",
};

describe("generateComposeOverride", () => {
  it("emits header comment with the stack_id", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    expect(out.startsWith("# Auto-generated by lich. Do not edit.\n")).toBe(
      true,
    );
    expect(out).toContain(`# stack_id: ${SINGLE_SERVICE_INPUT.stackId}\n`);
  });

  it("does NOT emit a top-level `version:` field", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);
    expect(parsed.version).toBeUndefined();
  });

  it("does NOT emit a top-level `name:` field", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);
    expect(parsed.name).toBeUndefined();
  });

  it("produces expected YAML for a single service with ports + env", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);

    expect(parsed.services).toBeDefined();
    expect(parsed.services.api).toEqual({
      image: "node:20",
      environment: {
        DATABASE_URL: "postgresql://user:pass@localhost:5432/db",
        LICH_STACK_ID: "dogfood-stack-a1b2c3d4",
      },
      ports: ["5847:3000"],
    });
  });

  it("gives each of multiple services its own block", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
        web: { ports: { http: { container: 3001, env: "PORT" } } },
      }),
      allocatedPorts: {
        compose: { api: { http: 5000 }, web: { http: 5001 } },
      },
      resolvedEnv: {
        api: { NODE_ENV: "dev" },
        web: { NODE_ENV: "dev" },
      },
      stackId: "stack-multi",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(Object.keys(parsed.services).sort()).toEqual(["api", "web"]);
    expect(parsed.services.api.ports).toEqual(["5000:3000"]);
    expect(parsed.services.web.ports).toEqual(["5001:3001"]);
  });

  it("omits a service that has no fields at all to emit", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
        worker: { compose_file: "extra.yaml" },
      }),
      allocatedPorts: { compose: { api: { http: 5000 } } },
      resolvedEnv: { api: { NODE_ENV: "dev" } },
      stackId: "stack-omit",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toBeDefined();
    expect(parsed.services.worker).toBeUndefined();
  });

  it("emits a service that declares ONLY `image:`", () => {
    const input: OverrideInput = {
      config: makeConfig({
        worker: { image: "redis:7-alpine" },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { worker: {} },
      stackId: "stack-image-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.worker).toEqual({ image: "redis:7-alpine" });
  });

  it("emits only `ports:` when a service has ports but no env", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
      }),
      allocatedPorts: { compose: { api: { http: 5000 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-ports-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toEqual({ ports: ["5000:3000"] });
    expect(parsed.services.api.environment).toBeUndefined();
  });

  it("emits `image:` + `environment:` when a service has env but no ports", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { image: "node:20" },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { api: { FOO: "bar" } },
      stackId: "stack-env-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toEqual({
      image: "node:20",
      environment: { FOO: "bar" },
    });
    expect(parsed.services.api.ports).toBeUndefined();
  });

  it("output round-trips through yaml.parse without error", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);
    expect(typeof parsed).toBe("object");
    expect(parsed).not.toBeNull();
  });

  it("handles the array form of `ports` by indexing on logical-name", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          ports: [
            { container: 3000, env: "PORT" },
            { container: 9229, env: "DEBUG_PORT" },
          ],
        },
      }),
      // array-form ports key by string index in the allocator
      allocatedPorts: { compose: { api: { "0": 5000, "1": 5001 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-array-ports",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toEqual(["5000:3000", "5001:9229"]);
  });

  it("skips port entries with no container declaration", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            // bare-number form: pins host but no container to bind
            pinned: 8080,
            http: { container: 3000, env: "PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { pinned: 8080, http: 5000 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-skip-pinned",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toEqual(["5000:3000"]);
  });

  it("accepts a strongly-typed PortDescriptor with `container`", () => {
    const httpPort: PortDescriptor = { container: 3000, env: "PORT" };
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          image: "node:20",
          ports: { http: httpPort },
        },
      }),
      allocatedPorts: { compose: { api: { http: 4242 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-typed-port",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toEqual(["4242:3000"]);
  });

  it("skips a typed PortDescriptor with no `container` field", () => {
    const noContainer: PortDescriptor = { env: "PORT" };
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          image: "node:20",
          ports: { http: noContainer },
        },
      }),
      allocatedPorts: { compose: { api: { http: 4242 } } },
      resolvedEnv: { api: { FOO: "bar" } },
      stackId: "stack-typed-port-no-container",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toBeUndefined();
    expect(parsed.services.api.environment).toEqual({ FOO: "bar" });
  });

  it("produces deterministic output regardless of key insertion order", () => {
    const a: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            http: { container: 3000, env: "PORT" },
            admin: { container: 3001, env: "ADMIN_PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { http: 5000, admin: 5001 } } },
      resolvedEnv: { api: { B: "2", A: "1" } },
      stackId: "stack-deterministic",
    };
    const b: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            admin: { container: 3001, env: "ADMIN_PORT" },
            http: { container: 3000, env: "PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { admin: 5001, http: 5000 } } },
      resolvedEnv: { api: { A: "1", B: "2" } },
      stackId: "stack-deterministic",
    };
    expect(generateComposeOverride(a)).toBe(generateComposeOverride(b));
  });

  it("when no services need overriding, still emits a valid (empty) document", () => {
    const input: OverrideInput = {
      config: makeConfig({ api: { compose_file: "extra.yaml" } }),
      allocatedPorts: { compose: {} },
      resolvedEnv: {},
      stackId: "stack-empty",
    };
    const out = generateComposeOverride(input);
    expect(out).toContain("# stack_id: stack-empty");
    const parsed = yamlParse(out);
    expect(parsed.services).toEqual({});
  });

  it("emits no `services:` entries for compose services not declared in config", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
      }),
      allocatedPorts: {
        compose: {
          api: { http: 5000 },
          ghost: { http: 6000 },
        },
      },
      resolvedEnv: { api: {}, ghost: { GHOST: "1" } },
      stackId: "stack-ghost",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(Object.keys(parsed.services)).toEqual(["api"]);
  });

  it("emits user-declared `healthcheck:` verbatim", () => {
    const healthcheck = {
      test: ["CMD-SHELL", "pg_isready -U postgres -d dogfood"],
      interval: "1s",
      timeout: "1s",
      retries: 30,
    };
    const input: OverrideInput = {
      config: makeConfig({
        postgres: { image: "postgres:16-alpine", healthcheck },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { postgres: {} },
      stackId: "stack-healthcheck",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.healthcheck).toEqual(healthcheck);
  });

  it("emits user-declared `volumes:` verbatim", () => {
    const volumes = ["./data:/var/lib/postgresql/data", "shared-vol:/shared"];
    const input: OverrideInput = {
      config: makeConfig({
        postgres: { image: "postgres:16-alpine", volumes },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { postgres: {} },
      stackId: "stack-volumes",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.volumes).toEqual(volumes);
  });

  it("emits user-declared `networks:` verbatim", () => {
    const networks = ["app-net", "db-net"];
    const input: OverrideInput = {
      config: makeConfig({
        api: { image: "node:20", networks },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { api: {} },
      stackId: "stack-networks",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.networks).toEqual(networks);
  });

  it("emits user-declared `profiles:` verbatim", () => {
    const profiles = ["debug", "tools"];
    const input: OverrideInput = {
      config: makeConfig({
        debugger: { image: "alpine", profiles },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { debugger: {} },
      stackId: "stack-profiles",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.debugger.profiles).toEqual(profiles);
  });

  it("emits user-declared `tmpfs:` (list form) verbatim", () => {
    const tmpfs = ["/var/lib/postgresql/data"];
    const input: OverrideInput = {
      config: makeConfig({
        postgres: { image: "postgres:16-alpine", tmpfs },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { postgres: {} },
      stackId: "stack-tmpfs-list",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.tmpfs).toEqual(tmpfs);
  });

  it("emits user-declared `tmpfs:` (string form) verbatim", () => {
    const input: OverrideInput = {
      config: makeConfig({
        postgres: {
          image: "postgres:16-alpine",
          tmpfs: "/var/lib/postgresql/data",
        },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { postgres: {} },
      stackId: "stack-tmpfs-string",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.tmpfs).toBe("/var/lib/postgresql/data");
  });

  it("merges user-declared `environment:` with resolved env (resolved wins)", () => {
    const input: OverrideInput = {
      config: makeConfig({
        postgres: {
          image: "postgres:16-alpine",
          environment: {
            POSTGRES_USER: "wrong",
            POSTGRES_DB: "dogfood",
          },
        },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: {
        postgres: {
          POSTGRES_USER: "postgres",
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/dogfood",
        },
      },
      stackId: "stack-env-merge",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.environment).toEqual({
      POSTGRES_USER: "postgres",
      POSTGRES_DB: "dogfood",
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/dogfood",
    });
  });

  it("emits user-declared `environment:` alone when no resolved env", () => {
    const input: OverrideInput = {
      config: makeConfig({
        postgres: {
          image: "postgres:16-alpine",
          environment: {
            POSTGRES_USER: "postgres",
            POSTGRES_PASSWORD: "postgres",
            POSTGRES_DB: "dogfood",
          },
        },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { postgres: {} },
      stackId: "stack-env-user-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.postgres.environment).toEqual({
      POSTGRES_USER: "postgres",
      POSTGRES_PASSWORD: "postgres",
      POSTGRES_DB: "dogfood",
    });
  });

  it("emits all passthroughs together in the stable field order", () => {
    const input: OverrideInput = {
      config: makeConfig({
        postgres: {
          image: "postgres:16-alpine",
          ports: { db: { container: 5432, env: "POSTGRES_HOST_PORT" } },
          environment: { POSTGRES_DB: "dogfood" },
          healthcheck: { test: ["CMD-SHELL", "pg_isready"] },
          volumes: ["shared:/shared"],
          networks: ["db-net"],
          profiles: ["db"],
          tmpfs: ["/var/lib/postgresql/data"],
        },
      }),
      allocatedPorts: { compose: { postgres: { db: 9001 } } },
      resolvedEnv: { postgres: {} },
      stackId: "stack-order",
    };
    const out = generateComposeOverride(input);
    const body = out
      .split("\n")
      .filter((l) => !l.startsWith("#"))
      .join("\n");
    const expectedOrder = [
      "image:",
      "environment:",
      "ports:",
      "healthcheck:",
      "volumes:",
      "networks:",
      "profiles:",
      "tmpfs:",
    ];
    const positions = expectedOrder.map((needle) => body.indexOf(needle));
    for (let i = 0; i < positions.length; i++) {
      expect(positions[i], `${expectedOrder[i]} should be present`).toBeGreaterThan(-1);
    }
    for (let i = 1; i < positions.length; i++) {
      expect(
        positions[i],
        `${expectedOrder[i]} should come after ${expectedOrder[i - 1]}`,
      ).toBeGreaterThan(positions[i - 1]);
    }
  });

  it("ignores non-object `environment:` shape and falls back to resolved env", () => {
    // list-form (`environment: ["KEY=value"]`) is left alone — override only merges map form
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          image: "node:20",
          environment: ["LEGACY_KEY=value"],
        },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { api: { FROM_PIPELINE: "ok" } },
      stackId: "stack-env-list-form",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.environment).toEqual({ FROM_PIPELINE: "ok" });
  });
});

describe("writeComposeOverride", () => {
  let home: string;
  let prevLichHome: string | undefined;

  beforeEach(() => {
    home = mkdtempSync(join(tmpdir(), "lich-override-test-"));
    prevLichHome = process.env.LICH_HOME;
    process.env.LICH_HOME = home;
  });

  afterEach(() => {
    if (prevLichHome === undefined) {
      delete process.env.LICH_HOME;
    } else {
      process.env.LICH_HOME = prevLichHome;
    }
    rmSync(home, { recursive: true, force: true });
  });

  it("writes to ${stackDir}/compose.override.yaml and returns that path", async () => {
    const path = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const expected = join(
      stackDir(SINGLE_SERVICE_INPUT.stackId),
      "compose.override.yaml",
    );
    expect(path).toBe(expected);

    const onDisk = readFileSync(path, "utf8");
    expect(onDisk).toBe(generateComposeOverride(SINGLE_SERVICE_INPUT));
  });

  it("creates the parent directory if it doesn't exist", async () => {
    const path = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const onDisk = readFileSync(path, "utf8");
    expect(onDisk.length).toBeGreaterThan(0);
  });

  it("is idempotent: same input -> identical file content", async () => {
    const path1 = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const content1 = readFileSync(path1, "utf8");

    const path2 = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const content2 = readFileSync(path2, "utf8");

    expect(path1).toBe(path2);
    expect(content1).toBe(content2);
  });
});
