import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parse as yamlParse } from "yaml";
import type { LichConfig } from "../../../src/config/types.js";
import {
  generateComposeOverride,
  writeComposeOverride,
  type OverrideInput,
} from "../../../src/compose/override.js";
import { stackDir } from "../../../src/state/directory.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

/**
 * Minimal LichConfig builder. Tests pass just the `services` shape they
 * care about — `version` is required for the type, everything else is
 * optional.
 */
function makeConfig(services: NonNullable<LichConfig["services"]>): LichConfig {
  return { version: "1", services };
}

/** A single-service config: one compose service `api` with one port. */
const SINGLE_SERVICE_CONFIG = makeConfig({
  api: {
    image: "node:20",
    ports: {
      http: { container: 3000, env: "PORT" },
    },
  },
});

/** Input matching `SINGLE_SERVICE_CONFIG` with one allocated port + env. */
const SINGLE_SERVICE_INPUT: OverrideInput = {
  config: SINGLE_SERVICE_CONFIG,
  allocatedPorts: {
    compose: {
      api: { http: 5847 },
    },
  },
  resolvedEnv: {
    api: {
      DATABASE_URL: "postgresql://user:pass@localhost:5432/db",
      LICH_STACK_ID: "dogfood-stack-a1b2c3d4",
    },
  },
  stackId: "dogfood-stack-a1b2c3d4",
};

// ---------------------------------------------------------------------------
// generateComposeOverride — pure function
// ---------------------------------------------------------------------------

describe("generateComposeOverride", () => {
  it("emits header comment with the stack_id", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    expect(out.startsWith("# Auto-generated by lich. Do not edit.\n")).toBe(
      true,
    );
    expect(out).toContain(`# stack_id: ${SINGLE_SERVICE_INPUT.stackId}\n`);
  });

  it("does NOT emit a top-level `version:` field", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);
    expect(parsed.version).toBeUndefined();
  });

  it("does NOT emit a top-level `name:` field", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);
    expect(parsed.name).toBeUndefined();
  });

  it("produces expected YAML for a single service with ports + env", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    const parsed = yamlParse(out);

    expect(parsed.services).toBeDefined();
    expect(parsed.services.api).toEqual({
      environment: {
        DATABASE_URL: "postgresql://user:pass@localhost:5432/db",
        LICH_STACK_ID: "dogfood-stack-a1b2c3d4",
      },
      ports: ["5847:3000"],
    });
  });

  it("gives each of multiple services its own block", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
        web: { ports: { http: { container: 3001, env: "PORT" } } },
      }),
      allocatedPorts: {
        compose: { api: { http: 5000 }, web: { http: 5001 } },
      },
      resolvedEnv: {
        api: { NODE_ENV: "dev" },
        web: { NODE_ENV: "dev" },
      },
      stackId: "stack-multi",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(Object.keys(parsed.services).sort()).toEqual(["api", "web"]);
    expect(parsed.services.api.ports).toEqual(["5000:3000"]);
    expect(parsed.services.web.ports).toEqual(["5001:3001"]);
  });

  it("omits a service that has neither ports nor env", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
        worker: { image: "node:20" },
      }),
      allocatedPorts: { compose: { api: { http: 5000 } } },
      resolvedEnv: { api: { NODE_ENV: "dev" } },
      stackId: "stack-omit",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toBeDefined();
    expect(parsed.services.worker).toBeUndefined();
  });

  it("emits only `ports:` when a service has ports but no env", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
      }),
      allocatedPorts: { compose: { api: { http: 5000 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-ports-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toEqual({ ports: ["5000:3000"] });
    expect(parsed.services.api.environment).toBeUndefined();
  });

  it("emits only `environment:` when a service has env but no ports", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: { image: "node:20" },
      }),
      allocatedPorts: { compose: {} },
      resolvedEnv: { api: { FOO: "bar" } },
      stackId: "stack-env-only",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api).toEqual({ environment: { FOO: "bar" } });
    expect(parsed.services.api.ports).toBeUndefined();
  });

  it("output round-trips through yaml.parse without error", () => {
    const out = generateComposeOverride(SINGLE_SERVICE_INPUT);
    // Should not throw; should produce an object.
    const parsed = yamlParse(out);
    expect(typeof parsed).toBe("object");
    expect(parsed).not.toBeNull();
  });

  it("handles the array form of `ports` by indexing on logical-name", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          ports: [
            { container: 3000, env: "PORT" },
            { container: 9229, env: "DEBUG_PORT" },
          ],
        },
      }),
      // Allocator keys for array-form ports are string indices.
      allocatedPorts: { compose: { api: { "0": 5000, "1": 5001 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-array-ports",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toEqual(["5000:3000", "5001:9229"]);
  });

  it("skips port entries with no container declaration", () => {
    const input: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            // Bare-number form: pins host port but doesn't declare container.
            // The override generator skips it (no host:container to emit).
            pinned: 8080,
            http: { container: 3000, env: "PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { pinned: 8080, http: 5000 } } },
      resolvedEnv: { api: {} },
      stackId: "stack-skip-pinned",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(parsed.services.api.ports).toEqual(["5000:3000"]);
  });

  it("produces deterministic output regardless of key insertion order", () => {
    const a: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            http: { container: 3000, env: "PORT" },
            admin: { container: 3001, env: "ADMIN_PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { http: 5000, admin: 5001 } } },
      resolvedEnv: { api: { B: "2", A: "1" } },
      stackId: "stack-deterministic",
    };
    // Same logical content, different insertion order.
    const b: OverrideInput = {
      config: makeConfig({
        api: {
          ports: {
            admin: { container: 3001, env: "ADMIN_PORT" },
            http: { container: 3000, env: "PORT" },
          },
        },
      }),
      allocatedPorts: { compose: { api: { admin: 5001, http: 5000 } } },
      resolvedEnv: { api: { A: "1", B: "2" } },
      stackId: "stack-deterministic",
    };
    expect(generateComposeOverride(a)).toBe(generateComposeOverride(b));
  });

  it("when no services need overriding, still emits a valid (empty) document", () => {
    const input: OverrideInput = {
      config: makeConfig({ api: { image: "node:20" } }),
      allocatedPorts: { compose: {} },
      resolvedEnv: {},
      stackId: "stack-empty",
    };
    const out = generateComposeOverride(input);
    // Header still present.
    expect(out).toContain("# stack_id: stack-empty");
    // Parses cleanly.
    const parsed = yamlParse(out);
    expect(parsed.services).toEqual({});
  });

  it("emits no `services:` entries for compose services not declared in config", () => {
    // If the allocator hands us ports for a service that doesn't exist
    // in the config, we ignore it — we can't know its container port.
    const input: OverrideInput = {
      config: makeConfig({
        api: { ports: { http: { container: 3000, env: "PORT" } } },
      }),
      allocatedPorts: {
        compose: {
          api: { http: 5000 },
          ghost: { http: 6000 },
        },
      },
      resolvedEnv: { api: {}, ghost: { GHOST: "1" } },
      stackId: "stack-ghost",
    };
    const parsed = yamlParse(generateComposeOverride(input));
    expect(Object.keys(parsed.services)).toEqual(["api"]);
  });
});

// ---------------------------------------------------------------------------
// writeComposeOverride — thin I/O wrapper
// ---------------------------------------------------------------------------

describe("writeComposeOverride", () => {
  let home: string;
  let prevLichHome: string | undefined;

  beforeEach(() => {
    home = mkdtempSync(join(tmpdir(), "lich-override-test-"));
    prevLichHome = process.env.LICH_HOME;
    process.env.LICH_HOME = home;
  });

  afterEach(() => {
    if (prevLichHome === undefined) {
      delete process.env.LICH_HOME;
    } else {
      process.env.LICH_HOME = prevLichHome;
    }
    rmSync(home, { recursive: true, force: true });
  });

  it("writes to ${stackDir}/compose.override.yaml and returns that path", async () => {
    const path = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const expected = join(
      stackDir(SINGLE_SERVICE_INPUT.stackId),
      "compose.override.yaml",
    );
    expect(path).toBe(expected);

    // File contents match the pure-function output exactly.
    const onDisk = readFileSync(path, "utf8");
    expect(onDisk).toBe(generateComposeOverride(SINGLE_SERVICE_INPUT));
  });

  it("creates the parent directory if it doesn't exist", async () => {
    // We just made a fresh tmpdir; no stack dir exists yet.
    const path = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const onDisk = readFileSync(path, "utf8");
    expect(onDisk.length).toBeGreaterThan(0);
  });

  it("is idempotent: same input -> identical file content", async () => {
    const path1 = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const content1 = readFileSync(path1, "utf8");

    const path2 = await writeComposeOverride(SINGLE_SERVICE_INPUT);
    const content2 = readFileSync(path2, "utf8");

    expect(path1).toBe(path2);
    expect(content1).toBe(content2);
  });
});
