import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import {
  BUILTIN_SUMMARIES,
  BUILTIN_LONG_HELP,
  BUILTIN_DISPLAY_ORDER,
} from "../src/commands/help";

const OUTPUT = resolve(import.meta.dir, "../../..", "docs/content/reference/cli.md");

const HEADER = [
  "<!--",
  "  AUTO-GENERATED by packages/lich/scripts/build-cli-reference.ts.",
  "  Do not edit by hand. Run `bun run build:cli-reference` to regenerate.",
  "  Source of truth: packages/lich/src/commands/help.ts",
  "-->",
  "",
  "# CLI reference",
  "",
  "Every lich command. The same content is what `lich --help` and",
  "`lich <command> --help` print — when you're at a terminal, the CLI",
  "itself is the most up-to-date source.",
  "",
].join("\n");

export function renderCliReference(
  summaries: Record<string, string>,
  longHelp: Record<string, string>,
  order: readonly string[],
): string {
  const sections = order.map((name) => {
    const summary = summaries[name];
    const help = longHelp[name];
    if (!summary || !help) {
      throw new Error(`Missing help data for command: ${name}`);
    }
    return [
      `## \`lich ${name}\``,
      "",
      summary,
      "",
      "```",
      help,
      "```",
      "",
    ].join("\n");
  });
  return HEADER + sections.join("\n");
}

function main(): void {
  const content = renderCliReference(BUILTIN_SUMMARIES, BUILTIN_LONG_HELP, BUILTIN_DISPLAY_ORDER);
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, content);
  console.log(`build-cli-reference: wrote ${OUTPUT}`);
}

if (import.meta.main) main();
