import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import {
  INTERPOLATION_KEYS,
  type InterpolationKey,
} from "../src/config/interpolation";

const OUTPUT = resolve(
  import.meta.dir,
  "../../..",
  "docs/content/reference/_generated/interpolation-keys.md",
);

export function renderInterpolationReference(keys: InterpolationKey[]): string {
  const header = [
    "<!--",
    "  AUTO-GENERATED by packages/lich/scripts/build-interpolation-reference.ts.",
    "  Do not edit by hand. Run `bun run build:interpolation-reference` to regenerate.",
    "  Source of truth: packages/lich/src/config/interpolation.ts",
    "  This snippet is @include'd into docs/content/reference/lich-yaml-spec.md.",
    "-->",
    "",
  ].join("\n");

  const tableLines = [
    "| Key | Resolves to | Evaluated |",
    "| --- | --- | --- |",
    ...keys.map(
      (k) => `| \`\${${k.pattern}}\` | ${k.resolves_to} | ${k.evaluated} |`,
    ),
  ];

  return header + tableLines.join("\n") + "\n";
}

function main(): void {
  const content = renderInterpolationReference(INTERPOLATION_KEYS);
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, content);
  console.log(`build-interpolation-reference: wrote ${OUTPUT}`);
}

if (import.meta.main) main();
