import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import {
  schema,
  composeServiceSchema,
  ownedServiceSchema,
  envGroupSchema,
  profileSchema,
  userCommandSchema,
  perServiceLifecycleSchema,
  topLevelLifecycleSchema,
  runtimeSchema,
} from "../src/config/schema";

const OUTPUT = resolve(
  import.meta.dir,
  "../../..",
  "docs/content/reference/_generated/yaml-fields.md",
);

export interface FieldRow {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface Section {
  title: string;
  anchor: string;
  schema: unknown;
}

export function describeType(propSchema: any): string {
  if (!propSchema || typeof propSchema !== "object") return "any";
  if (propSchema.enum) {
    return propSchema.enum.map((v: unknown) => JSON.stringify(v)).join(" \\| ");
  }
  // oneOf expresses two distinct shapes: type-unions (`int | object`) where
  // each arm carries a `type`, or intra-type mutual exclusion (one-of fields
  // A/B on an object) where arms only carry `required`. The latter renders
  // best as the outer container's type — fall through to the type check below.
  if (propSchema.oneOf && propSchema.oneOf.some((arm: any) => arm?.type !== undefined)) {
    return propSchema.oneOf.map(describeType).join(" \\| ");
  }
  if (Array.isArray(propSchema.type)) return propSchema.type.join(" \\| ");
  if (propSchema.type === "array") {
    if (propSchema.items?.type) return `${propSchema.items.type}[]`;
    return "array";
  }
  if (propSchema.type === "object") {
    return "object";
  }
  return propSchema.type ?? "any";
}

export function walkObjectSchema(s: any): FieldRow[] {
  if (!s || !s.properties) return [];
  const required = new Set<string>(s.required ?? []);
  return Object.entries(s.properties as Record<string, any>).map(([name, propSchema]) => ({
    name,
    type: describeType(propSchema),
    required: required.has(name),
    description: propSchema.description ?? "—",
  }));
}

function tableForSection(section: Section): string {
  const rows = walkObjectSchema(section.schema);
  if (rows.length === 0) return "";
  const lines = [
    "",
    `## ${section.title} {#${section.anchor}}`,
    "",
    "| Field | Type | Required | Description |",
    "| --- | --- | --- | --- |",
    ...rows.map(
      (r) =>
        `| \`${r.name}\` | \`${r.type}\` | ${r.required ? "yes" : "no"} | ${r.description} |`,
    ),
    "",
  ];
  return lines.join("\n");
}

export function renderYamlReference(sections: Section[]): string {
  const header = [
    "<!--",
    "  AUTO-GENERATED by packages/lich/scripts/build-yaml-reference.ts.",
    "  Do not edit by hand. Run `bun run build:yaml-reference` to regenerate.",
    "  Source of truth: packages/lich/src/config/schema.ts",
    "  This snippet is @include'd into docs/content/reference/lich-yaml-spec.md.",
    "-->",
    "",
  ].join("\n");
  return header + sections.map(tableForSection).filter(Boolean).join("\n");
}

const SECTIONS: Section[] = [
  { title: "Top-level keys", anchor: "top-level", schema },
  { title: "Compose service (`services.<name>`)", anchor: "services", schema: composeServiceSchema },
  { title: "Owned service (`owned.<name>`)", anchor: "owned", schema: ownedServiceSchema },
  { title: "env_group (`env_groups.<name>`)", anchor: "env-groups", schema: envGroupSchema },
  { title: "Profile (`profiles.<name>`)", anchor: "profiles", schema: profileSchema },
  { title: "Custom command (`commands.<name>`)", anchor: "commands", schema: userCommandSchema },
  { title: "Per-service lifecycle (`services.*.lifecycle` / `owned.*.lifecycle`)", anchor: "lifecycle-per-service", schema: perServiceLifecycleSchema },
  { title: "Top-level lifecycle (`lifecycle`)", anchor: "lifecycle-top-level", schema: topLevelLifecycleSchema },
  { title: "Runtime (`runtime`)", anchor: "runtime", schema: runtimeSchema },
];

function main(): void {
  const content = renderYamlReference(SECTIONS);
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, content);
  console.log(`build-yaml-reference: wrote ${OUTPUT}`);
}

if (import.meta.main) main();
