#!/usr/bin/env bun
/**
 * Emit `embedded-ui.generated.ts` from the Vite dashboard build at
 * `src/daemon/dashboard/ui/dist/`, inlining each file as base64. Run by
 * `build:ui:embed` between `build:ui` and `build:daemon` so the
 * compiled daemon binary ships with the SPA bytes embedded. Committed
 * as a build artifact; empty manifest falls back to placeholder HTML.
 */
import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const UI_DIST = join(packageRoot, "src/daemon/dashboard/ui/dist");
const OUT_FILE = join(
  packageRoot,
  "src/daemon/dashboard/embedded-ui.generated.ts",
);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (entry.isFile()) out.push(p);
  }
  return out;
}

function contentTypeFor(path: string): string {
  if (path.endsWith(".html")) return "text/html; charset=utf-8";
  if (path.endsWith(".js") || path.endsWith(".mjs"))
    return "text/javascript; charset=utf-8";
  if (path.endsWith(".css")) return "text/css; charset=utf-8";
  if (path.endsWith(".json")) return "application/json; charset=utf-8";
  if (path.endsWith(".svg")) return "image/svg+xml";
  if (path.endsWith(".png")) return "image/png";
  if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
  if (path.endsWith(".webp")) return "image/webp";
  if (path.endsWith(".woff2")) return "font/woff2";
  if (path.endsWith(".woff")) return "font/woff";
  if (path.endsWith(".map")) return "application/json; charset=utf-8";
  if (path.endsWith(".ico")) return "image/x-icon";
  if (path.endsWith(".txt")) return "text/plain; charset=utf-8";
  return "application/octet-stream";
}

let entries: string[] = [];
let totalBytes = 0;
let fileCount = 0;

if (existsSync(UI_DIST)) {
  const files = walk(UI_DIST).sort();
  for (const file of files) {
    const rel = relative(UI_DIST, file).split("\\").join("/");
    const bytes = readFileSync(file);
    totalBytes += bytes.length;
    fileCount += 1;
    const b64 = bytes.toString("base64");
    entries.push(
      `  ${JSON.stringify(rel)}: { b64: ${JSON.stringify(b64)}, contentType: ${JSON.stringify(contentTypeFor(rel))} },`,
    );
  }
} else {
  // UI not built — emit empty map; daemon falls back to placeholder.
}

const banner = `// AUTO-GENERATED by scripts/embed-ui.ts — DO NOT EDIT
//
// Regenerated by \`bun run build:ui:embed\` (chained from \`bun run build\`).
// Source: src/daemon/dashboard/ui/dist/ (Vite output).
// Files: ${fileCount}, raw bytes: ${totalBytes}.
//
// Committed as a build artifact: fresh checkouts get the most-recent
// build's manifest so unit tests + dev mode work without re-running the
// UI build. Re-run \`bun run build\` before shipping a release.

`;

const body = `export interface EmbeddedAsset {
  bytes: Uint8Array;
  contentType: string;
}

const _cache: Record<string, EmbeddedAsset> = Object.create(null);
const _raw: Record<string, { b64: string; contentType: string }> = {
${entries.join("\n")}
};

/**
 * Get an embedded asset by path (e.g. "index.html", "assets/index-abc.js").
 * Returns undefined if no such file is embedded. Decoded bytes are cached
 * after first access.
 */
export function getEmbeddedAsset(path: string): EmbeddedAsset | undefined {
  const cached = _cache[path];
  if (cached) return cached;
  const raw = _raw[path];
  if (!raw) return undefined;
  // atob → Latin-1 string → byte array. Works in Bun and Node 20+.
  const decoded = atob(raw.b64);
  const bytes = new Uint8Array(decoded.length);
  for (let i = 0; i < decoded.length; i++) bytes[i] = decoded.charCodeAt(i);
  const asset: EmbeddedAsset = { bytes, contentType: raw.contentType };
  _cache[path] = asset;
  return asset;
}

/** List all embedded asset paths (alphabetical). */
export function listEmbeddedAssets(): readonly string[] {
  return Object.keys(_raw);
}

/** True iff any assets are embedded — false on a stub manifest. */
export function hasEmbeddedAssets(): boolean {
  return Object.keys(_raw).length > 0;
}
`;

writeFileSync(OUT_FILE, banner + body, "utf8");
const tsKb = Math.round(((banner + body).length / 1024) * 10) / 10;
console.log(
  `embed-ui: wrote ${OUT_FILE} (${fileCount} files, ${totalBytes} bytes raw → ${tsKb} KB TS)`,
);
