/**
 * Generated `.env.<service>` file writer (Plan 16 / LEV-183).
 *
 * After per-service env resolution (LEV-182) the runtime drops a dotenv-format
 * snapshot of each running service's env under
 * `.lich/state/<worktreeKey>/env/<service>.env`. The files are:
 *
 *  - **Inspectable** — `cat .lich/state/<wt>/env/api.env` shows exactly what
 *    the api service received.
 *  - **Debuggable** — `lich env resolve <service>` (LEV-184) regenerates
 *    and prints the same content.
 *  - **Portable** — standard dotenv syntax, source'able by anything that reads
 *    `.env` (CI runners, shell, dotenv libraries).
 *
 * The format is intentionally simple: one `KEY=value` per line with quoting
 * applied only when needed (whitespace, quotes, newlines, `=`, `#`). Re-runs
 * overwrite cleanly — no append, no diff merging.
 *
 * Encryption-at-rest is out of scope (LEV-183 deliberately): the parent
 * directory `.lich/state/` is gitignored. Projects that need sealed
 * secrets in dev have bigger problems than this writer.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

/**
 * Characters that force the value to be wrapped in double quotes per dotenv
 * conventions:
 *   - whitespace (so `KEY=hello world` doesn't parse as `KEY=hello` + garbage)
 *   - `=` (so `KEY=a=b` round-trips correctly)
 *   - `#` (so a literal `#` isn't read as a comment)
 *   - `"` (always quoted so the escape rule applies uniformly)
 *   - `\` (so a literal backslash doesn't get eaten by an un-escaped pass)
 *   - newline (`\n` / `\r`) — must be escaped inside quotes
 */
function needsQuoting(value: string): boolean {
  return /[\s"#=\\\n\r]/.test(value);
}

/**
 * Escape a value's contents for inclusion inside double quotes. Order matters:
 * backslash first so subsequent escapes don't get double-escaped.
 *
 *   `\`  → `\\`
 *   `"`  → `\"`
 *   `\n` → `\\n` (literal backslash + n, not a real newline — so the file is
 *                 single-line per entry and grep/cat friendly)
 *   `\r` → `\\r`
 */
function escapeQuoted(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

/**
 * Render a single `KEY=value` line. Values that need quoting are wrapped in
 * double quotes with the necessary escapes; otherwise emitted bare.
 */
function formatEntry(key: string, value: string): string {
  if (needsQuoting(value)) {
    return `${key}="${escapeQuoted(value)}"`;
  }
  return `${key}=${value}`;
}

/**
 * Format an env map as a dotenv file body, header included. Pure function so
 * tests can assert content without disk I/O. Keys are emitted in insertion
 * order — the caller controls layout (the resolver's order is already the
 * "natural" order: importAll first, explicit entries last).
 *
 * `now` is injected so tests can pin the ISO timestamp; production callers
 * should pass `new Date()`.
 */
export function formatEnvFile(
  env: Record<string, string>,
  now: Date = new Date(),
): string {
  const header = [
    `# generated by lich dev on ${now.toISOString()} — DO NOT EDIT`,
    `# regenerate via: lich env resolve <service>`,
  ];
  const lines = [
    ...header,
    ...Object.entries(env).map(([k, v]) => formatEntry(k, v)),
  ];
  // Trailing newline so `cat` doesn't leave the prompt mid-line and tools that
  // require POSIX-text-file shape are happy.
  return lines.join('\n') + '\n';
}

/**
 * Write a resolved env map to `absPath` in dotenv format. Creates parent
 * directories as needed. Overwrites any existing file at the path (no append,
 * no merge — the writer is a snapshot, not a journal).
 *
 * Encoding is UTF-8. Returns once the bytes are flushed; the caller awaits
 * before treating the file as readable downstream.
 */
export async function writeEnvFile(
  absPath: string,
  env: Record<string, string>,
): Promise<void> {
  await mkdir(dirname(absPath), { recursive: true });
  await writeFile(absPath, formatEnvFile(env), 'utf8');
}
